[build.environment]
NETLIFY_NEXT_SKEW_PROTECTION = "true"

[[redirects]]
from = "https://codebundle.jkjitendra.in/"
to = "/codebundle"
status = 200
force = true

[[redirects]]
from = "http://codebundle.jkjitendra.in/"
to = "/codebundle"
status = 200
force = true

[[redirects]]
from = "https://jkjitendra.in/*"
to = "https://www.jkjitendra.in/:splat"
status = 301
force = true

[[redirects]]
from = "http://jkjitendra.in/*"
to = "https://www.jkjitendra.in/:splat"
status = 301
force = true